function [fitresult, gof] = FRAPfit(frames, data,color)
%CREATEFIT(FRAMES,G)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : frames
%      Y Output: g
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jun-2016 14:50:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frames, data );

% Set up fittype and options.
%ft = fittype( 'a - c*exp(-t/tau)-d*t', 'independent', 't', 'dependent', 'y' );
% ft = fittype( 'a*(1-exp(-t/tau))-d*t', 'independent', 't', 'dependent', 'y' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.Lower = [-Inf -Inf -Inf];
% opts.StartPoint = [1 1 1];

if strcmp(color, 'g--')
ft = fittype( 'a*(1-exp(-t/tau))', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [1 1];

else
% ft = fittype( 'a*(1-exp(-t/tau))-d*t', 'independent', 't', 'dependent', 'y' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.Lower = [-Inf -Inf -Inf];
% opts.StartPoint = [.4576 0.6324 0.9134];

ft = fittype( 'a*(1-exp(-t/tau))', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [1 1];

end


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', ' Fit to: a*(1- exp(-t/tau))-d*t' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData, color );
legend( h, 'data', 'fit', 'Location', 'NorthEast' );
% Label axes
xlabel frames
ylabel data
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel frames
ylabel data
grid on


