function [fitresult, gof] = FitExpDecay(pos1, curve1, maxIndex, initialguess)
%CREATEFIT(POS1,CURVE1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pos1
%      Y Output: curve1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2016 10:06:40


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pos1, curve1);

% Set up fittype and options.
ft = fittype( 'exp(-(x-a)/b)+c', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData < pos1(maxIndex);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = initialguess;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData, excludedPoints );
% legend( h, 'curve1 vs. pos1', 'Excluded curve1 vs. pos1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
% xlabel pos1
% ylabel curve1
% grid on


