function [fitresult, gof] = tanhFit(posg, testg, index)
%CREATEFIT(POSG,TESTG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : posg
%      Y Output: testg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-May-2016 13:48:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( posg, testg);

% Set up fittype and options.
ft = fittype( 'a*tanh(-(x-b)/c)+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.63235924622541 100 0.278498218867048 0.546881519204984];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
if index==1
% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'testg vs. posg', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel posg
ylabel testg
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel posg
ylabel testg
grid on
end


